/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutNegativacaoRouteImport } from './routes/_layout/negativacao'
import { Route as LayoutCronogramaRouteImport } from './routes/_layout/cronograma'
import { Route as LayoutConsultasRouteImport } from './routes/_layout/consultas'
import { Route as LayoutConfiguracoesRouteImport } from './routes/_layout/configuracoes'
import { Route as LayoutCobrancaRouteImport } from './routes/_layout/cobranca'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutNegativacaoIndexRouteImport } from './routes/_layout/negativacao/index'
import { Route as LayoutNegativacaoRetiradasRouteImport } from './routes/_layout/negativacao/retiradas'
import { Route as LayoutCobrancaNovoProcessoRouteImport } from './routes/_layout/cobranca/novo-processo'
import { Route as LayoutCobrancaMinhasDistribuicoesRouteImport } from './routes/_layout/cobranca/minhas-distribuicoes'
import { Route as LayoutCobrancaMeusProcessosRouteImport } from './routes/_layout/cobranca/meus-processos'
import { Route as LayoutAdminTratativaInternaRouteImport } from './routes/_layout/admin/tratativa-interna'
import { Route as LayoutAdminEmpreendimentoRouteImport } from './routes/_layout/admin/empreendimento'
import { Route as LayoutAdminCvSiengeRouteImport } from './routes/_layout/admin/cv-sienge'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNegativacaoRoute = LayoutNegativacaoRouteImport.update({
  id: '/negativacao',
  path: '/negativacao',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCronogramaRoute = LayoutCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsultasRoute = LayoutConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfiguracoesRoute = LayoutConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCobrancaRoute = LayoutCobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNegativacaoIndexRoute = LayoutNegativacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutNegativacaoRoute,
} as any)
const LayoutNegativacaoRetiradasRoute =
  LayoutNegativacaoRetiradasRouteImport.update({
    id: '/retiradas',
    path: '/retiradas',
    getParentRoute: () => LayoutNegativacaoRoute,
  } as any)
const LayoutCobrancaNovoProcessoRoute =
  LayoutCobrancaNovoProcessoRouteImport.update({
    id: '/novo-processo',
    path: '/novo-processo',
    getParentRoute: () => LayoutCobrancaRoute,
  } as any)
const LayoutCobrancaMinhasDistribuicoesRoute =
  LayoutCobrancaMinhasDistribuicoesRouteImport.update({
    id: '/minhas-distribuicoes',
    path: '/minhas-distribuicoes',
    getParentRoute: () => LayoutCobrancaRoute,
  } as any)
const LayoutCobrancaMeusProcessosRoute =
  LayoutCobrancaMeusProcessosRouteImport.update({
    id: '/meus-processos',
    path: '/meus-processos',
    getParentRoute: () => LayoutCobrancaRoute,
  } as any)
const LayoutAdminTratativaInternaRoute =
  LayoutAdminTratativaInternaRouteImport.update({
    id: '/tratativa-interna',
    path: '/tratativa-interna',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminEmpreendimentoRoute =
  LayoutAdminEmpreendimentoRouteImport.update({
    id: '/empreendimento',
    path: '/empreendimento',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminCvSiengeRoute = LayoutAdminCvSiengeRouteImport.update({
  id: '/cv-sienge',
  path: '/cv-sienge',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/cobranca': typeof LayoutCobrancaRouteWithChildren
  '/configuracoes': typeof LayoutConfiguracoesRoute
  '/consultas': typeof LayoutConsultasRoute
  '/cronograma': typeof LayoutCronogramaRoute
  '/negativacao': typeof LayoutNegativacaoRouteWithChildren
  '/admin/cv-sienge': typeof LayoutAdminCvSiengeRoute
  '/admin/empreendimento': typeof LayoutAdminEmpreendimentoRoute
  '/admin/tratativa-interna': typeof LayoutAdminTratativaInternaRoute
  '/cobranca/meus-processos': typeof LayoutCobrancaMeusProcessosRoute
  '/cobranca/minhas-distribuicoes': typeof LayoutCobrancaMinhasDistribuicoesRoute
  '/cobranca/novo-processo': typeof LayoutCobrancaNovoProcessoRoute
  '/negativacao/retiradas': typeof LayoutNegativacaoRetiradasRoute
  '/negativacao/': typeof LayoutNegativacaoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/cobranca': typeof LayoutCobrancaRouteWithChildren
  '/configuracoes': typeof LayoutConfiguracoesRoute
  '/consultas': typeof LayoutConsultasRoute
  '/cronograma': typeof LayoutCronogramaRoute
  '/': typeof LayoutIndexRoute
  '/admin/cv-sienge': typeof LayoutAdminCvSiengeRoute
  '/admin/empreendimento': typeof LayoutAdminEmpreendimentoRoute
  '/admin/tratativa-interna': typeof LayoutAdminTratativaInternaRoute
  '/cobranca/meus-processos': typeof LayoutCobrancaMeusProcessosRoute
  '/cobranca/minhas-distribuicoes': typeof LayoutCobrancaMinhasDistribuicoesRoute
  '/cobranca/novo-processo': typeof LayoutCobrancaNovoProcessoRoute
  '/negativacao/retiradas': typeof LayoutNegativacaoRetiradasRoute
  '/negativacao': typeof LayoutNegativacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/cobranca': typeof LayoutCobrancaRouteWithChildren
  '/_layout/configuracoes': typeof LayoutConfiguracoesRoute
  '/_layout/consultas': typeof LayoutConsultasRoute
  '/_layout/cronograma': typeof LayoutCronogramaRoute
  '/_layout/negativacao': typeof LayoutNegativacaoRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/cv-sienge': typeof LayoutAdminCvSiengeRoute
  '/_layout/admin/empreendimento': typeof LayoutAdminEmpreendimentoRoute
  '/_layout/admin/tratativa-interna': typeof LayoutAdminTratativaInternaRoute
  '/_layout/cobranca/meus-processos': typeof LayoutCobrancaMeusProcessosRoute
  '/_layout/cobranca/minhas-distribuicoes': typeof LayoutCobrancaMinhasDistribuicoesRoute
  '/_layout/cobranca/novo-processo': typeof LayoutCobrancaNovoProcessoRoute
  '/_layout/negativacao/retiradas': typeof LayoutNegativacaoRetiradasRoute
  '/_layout/negativacao/': typeof LayoutNegativacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/cobranca'
    | '/configuracoes'
    | '/consultas'
    | '/cronograma'
    | '/negativacao'
    | '/admin/cv-sienge'
    | '/admin/empreendimento'
    | '/admin/tratativa-interna'
    | '/cobranca/meus-processos'
    | '/cobranca/minhas-distribuicoes'
    | '/cobranca/novo-processo'
    | '/negativacao/retiradas'
    | '/negativacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/cobranca'
    | '/configuracoes'
    | '/consultas'
    | '/cronograma'
    | '/'
    | '/admin/cv-sienge'
    | '/admin/empreendimento'
    | '/admin/tratativa-interna'
    | '/cobranca/meus-processos'
    | '/cobranca/minhas-distribuicoes'
    | '/cobranca/novo-processo'
    | '/negativacao/retiradas'
    | '/negativacao'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/cobranca'
    | '/_layout/configuracoes'
    | '/_layout/consultas'
    | '/_layout/cronograma'
    | '/_layout/negativacao'
    | '/_layout/'
    | '/_layout/admin/cv-sienge'
    | '/_layout/admin/empreendimento'
    | '/_layout/admin/tratativa-interna'
    | '/_layout/cobranca/meus-processos'
    | '/_layout/cobranca/minhas-distribuicoes'
    | '/_layout/cobranca/novo-processo'
    | '/_layout/negativacao/retiradas'
    | '/_layout/negativacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/negativacao': {
      id: '/_layout/negativacao'
      path: '/negativacao'
      fullPath: '/negativacao'
      preLoaderRoute: typeof LayoutNegativacaoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cronograma': {
      id: '/_layout/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof LayoutCronogramaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/consultas': {
      id: '/_layout/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof LayoutConsultasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/configuracoes': {
      id: '/_layout/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof LayoutConfiguracoesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cobranca': {
      id: '/_layout/cobranca'
      path: '/cobranca'
      fullPath: '/cobranca'
      preLoaderRoute: typeof LayoutCobrancaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/negativacao/': {
      id: '/_layout/negativacao/'
      path: '/'
      fullPath: '/negativacao/'
      preLoaderRoute: typeof LayoutNegativacaoIndexRouteImport
      parentRoute: typeof LayoutNegativacaoRoute
    }
    '/_layout/negativacao/retiradas': {
      id: '/_layout/negativacao/retiradas'
      path: '/retiradas'
      fullPath: '/negativacao/retiradas'
      preLoaderRoute: typeof LayoutNegativacaoRetiradasRouteImport
      parentRoute: typeof LayoutNegativacaoRoute
    }
    '/_layout/cobranca/novo-processo': {
      id: '/_layout/cobranca/novo-processo'
      path: '/novo-processo'
      fullPath: '/cobranca/novo-processo'
      preLoaderRoute: typeof LayoutCobrancaNovoProcessoRouteImport
      parentRoute: typeof LayoutCobrancaRoute
    }
    '/_layout/cobranca/minhas-distribuicoes': {
      id: '/_layout/cobranca/minhas-distribuicoes'
      path: '/minhas-distribuicoes'
      fullPath: '/cobranca/minhas-distribuicoes'
      preLoaderRoute: typeof LayoutCobrancaMinhasDistribuicoesRouteImport
      parentRoute: typeof LayoutCobrancaRoute
    }
    '/_layout/cobranca/meus-processos': {
      id: '/_layout/cobranca/meus-processos'
      path: '/meus-processos'
      fullPath: '/cobranca/meus-processos'
      preLoaderRoute: typeof LayoutCobrancaMeusProcessosRouteImport
      parentRoute: typeof LayoutCobrancaRoute
    }
    '/_layout/admin/tratativa-interna': {
      id: '/_layout/admin/tratativa-interna'
      path: '/tratativa-interna'
      fullPath: '/admin/tratativa-interna'
      preLoaderRoute: typeof LayoutAdminTratativaInternaRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/empreendimento': {
      id: '/_layout/admin/empreendimento'
      path: '/empreendimento'
      fullPath: '/admin/empreendimento'
      preLoaderRoute: typeof LayoutAdminEmpreendimentoRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/cv-sienge': {
      id: '/_layout/admin/cv-sienge'
      path: '/cv-sienge'
      fullPath: '/admin/cv-sienge'
      preLoaderRoute: typeof LayoutAdminCvSiengeRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminCvSiengeRoute: typeof LayoutAdminCvSiengeRoute
  LayoutAdminEmpreendimentoRoute: typeof LayoutAdminEmpreendimentoRoute
  LayoutAdminTratativaInternaRoute: typeof LayoutAdminTratativaInternaRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminCvSiengeRoute: LayoutAdminCvSiengeRoute,
  LayoutAdminEmpreendimentoRoute: LayoutAdminEmpreendimentoRoute,
  LayoutAdminTratativaInternaRoute: LayoutAdminTratativaInternaRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutCobrancaRouteChildren {
  LayoutCobrancaMeusProcessosRoute: typeof LayoutCobrancaMeusProcessosRoute
  LayoutCobrancaMinhasDistribuicoesRoute: typeof LayoutCobrancaMinhasDistribuicoesRoute
  LayoutCobrancaNovoProcessoRoute: typeof LayoutCobrancaNovoProcessoRoute
}

const LayoutCobrancaRouteChildren: LayoutCobrancaRouteChildren = {
  LayoutCobrancaMeusProcessosRoute: LayoutCobrancaMeusProcessosRoute,
  LayoutCobrancaMinhasDistribuicoesRoute:
    LayoutCobrancaMinhasDistribuicoesRoute,
  LayoutCobrancaNovoProcessoRoute: LayoutCobrancaNovoProcessoRoute,
}

const LayoutCobrancaRouteWithChildren = LayoutCobrancaRoute._addFileChildren(
  LayoutCobrancaRouteChildren,
)

interface LayoutNegativacaoRouteChildren {
  LayoutNegativacaoRetiradasRoute: typeof LayoutNegativacaoRetiradasRoute
  LayoutNegativacaoIndexRoute: typeof LayoutNegativacaoIndexRoute
}

const LayoutNegativacaoRouteChildren: LayoutNegativacaoRouteChildren = {
  LayoutNegativacaoRetiradasRoute: LayoutNegativacaoRetiradasRoute,
  LayoutNegativacaoIndexRoute: LayoutNegativacaoIndexRoute,
}

const LayoutNegativacaoRouteWithChildren =
  LayoutNegativacaoRoute._addFileChildren(LayoutNegativacaoRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutCobrancaRoute: typeof LayoutCobrancaRouteWithChildren
  LayoutConfiguracoesRoute: typeof LayoutConfiguracoesRoute
  LayoutConsultasRoute: typeof LayoutConsultasRoute
  LayoutCronogramaRoute: typeof LayoutCronogramaRoute
  LayoutNegativacaoRoute: typeof LayoutNegativacaoRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutCobrancaRoute: LayoutCobrancaRouteWithChildren,
  LayoutConfiguracoesRoute: LayoutConfiguracoesRoute,
  LayoutConsultasRoute: LayoutConsultasRoute,
  LayoutCronogramaRoute: LayoutCronogramaRoute,
  LayoutNegativacaoRoute: LayoutNegativacaoRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
